# Generated by Django 5.2 on 2025-05-26 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lounge", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArcadeMachine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="사용 가능 여부"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ArcadeMachineTimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="시작 시간")),
                ("end_time", models.DateTimeField(verbose_name="종료 시간")),
                (
                    "booked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="예약 시간"
                    ),
                ),
                (
                    "arcade_machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lounge.arcademachine",
                        verbose_name="아케이드 머신",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="예약자",
                    ),
                ),
            ],
            options={
                "ordering": ["start_time"],
                "unique_together": {("arcade_machine", "start_time")},
            },
        ),
    ]
