# Generated by Django 5.1.7 on 2025-04-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0002_rename_timeslot_inductiontimeslot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inductiontimeslot",
            name="booked_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="예약 시간"),
        ),
    ]
