# Generated by Django 5.2 on 2025-05-26 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="기구명"
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="사용 가능 여부"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Treadmill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="기구명"
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="사용 가능 여부"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CycleTimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="시작 시간")),
                ("end_time", models.DateTimeField(verbose_name="종료 시간")),
                (
                    "booked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="예약 확정 시간"
                    ),
                ),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gym.cycle",
                        verbose_name="사이클",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="예약자",
                    ),
                ),
            ],
            options={
                "ordering": ["start_time"],
                "abstract": False,
                "unique_together": {("cycle", "start_time")},
            },
        ),
        migrations.CreateModel(
            name="TreadmillTimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="시작 시간")),
                ("end_time", models.DateTimeField(verbose_name="종료 시간")),
                (
                    "booked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="예약 확정 시간"
                    ),
                ),
                (
                    "treadmill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gym.treadmill",
                        verbose_name="런닝머신",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="예약자",
                    ),
                ),
            ],
            options={
                "ordering": ["start_time"],
                "abstract": False,
                "unique_together": {("treadmill", "start_time")},
            },
        ),
    ]
