# Generated by Django 5.2 on 2025-05-26 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gym", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cycle",
            name="name",
        ),
        migrations.RemoveField(
            model_name="treadmill",
            name="name",
        ),
    ]
